name: Build and Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm ci && (cd client && npm ci) && (cd reporter-client && npm ci)
            - name: Build
              run: npm run build
            - name: Build Linux
              run: npm run build:linux
            - name: Upload AppImage
              uses: actions/upload-artifact@v3
              with:
                  name: Lumi-Linux
                  path: dist/*.AppImage

    build-mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm ci && (cd client && npm ci) && (cd reporter-client && npm ci)
            - name: Build
              run: npm run build
            - name: Build macOS
              run: npm run build:mac:dev
            - name: Upload macOS
              uses: actions/upload-artifact@v3
              with:
                  name: Lumi-macOS
                  path: dist/*.dmg

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm ci && (cd client && npm ci) && (cd reporter-client && npm ci)
            - name: Build
              run: npm run build
            - name: Build Windows
              run: npm run build:win
            - name: Upload Windows
              uses: actions/upload-artifact@v3
              with:
                  name: Lumi-Windows
                  path: dist/*.exe

    release:
        needs: [build-linux, build-mac, build-windows]
        runs-on: ubuntu-latest
        steps:
            - name: Download Linux artifacts
              uses: actions/download-artifact@v3
              with:
                  name: Lumi-Linux
                  path: artifacts/linux
            - name: Download macOS artifacts
              uses: actions/download-artifact@v3
              with:
                  name: Lumi-macOS
                  path: artifacts/mac
            - name: Download Windows artifacts
              uses: actions/download-artifact@v3
              with:
                  name: Lumi-Windows
                  path: artifacts/windows
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      artifacts/linux/*
                      artifacts/mac/*
                      artifacts/windows/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
